on:
  # cron job per day
  # schedule:
    # - cron: "0 0 * * *"
  # manual trigger
  workflow_dispatch:
name: Sync and create PR from azure mongo database
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run genreate-document action
        uses: ./.github/actions/generate-document
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync and create PR from azure mongo database"
          title: "Sync and create PR from azure mongo database"
          body: "Sync and create PR from azure mongo database"
          branch: "new-i18n"
          delete-branch: true



